### ISSUE TITLE
Stop serve break when there is a compilation error

### ISSUE THREAD

**Issue by dagadbm** [maizzle/framework#120]
### Description:
Everytime I am developing and if I have a syntax error, for example, while importing components amongst the mid tipping and the auto saving the compiler throws an error and breaks my development flow.
Would it be possible to just silenntly catch these exceptions, throw them in the consnole but not really halt the server? Just use the previously working compiled version. Its better than always having to do maizzle serve everytime

**Comment by cossssmin** [comment]
Sorry, but the amount of overhead and potential issues this would introduce is not worth the convenience.

**Comment by dagadbm** [comment]
alright. thought it would be a simple try catch when runninng the serve command and not really very deep changes to how the dev environnment is set up

**Comment by cossssmin** [comment]
Sure, but if something in the build chain breaks, I would expect to see the error stack and my build to break - not keep on going while there's something broken in its dependency chain.

I'll be closing this for now, but maybe we'll revisit it once we have a proper test suite and CI in place - I'm working on this for `v1.0.0` 👍

**Comment by dagadbm** [comment]
Try to at least have more explicit errors everytime my nunjuck template has
error its impossible to understand where they are :(

Also thank you so so much for this.
It was a lifesaver having never done emails before

**Comment by dagadbm** [comment]
sorry to comment on this again but is there a quick way for me to know which file is breaking the build at least?

```
❯ npm run start

> @ start /Users/david.maia/work/unbabel/email-templates
> maizzle serve

✖ Build failed
{ Template render error: (unknown path) [Line 52, Column 35]
  parseAggregate: expected comma after expression
    at Object._prettifyError (/.../node_modules/nunjucks/src/lib.js:36:11)
    at Template.render (/...node_modules/nunjucks/src/environment.js:536:21)
    at Environment.renderString (/.../src/environment.js:378:17)
    at module.exports (/.../node_modules/@maizzle/framework/src/generators/output/toString.js:50:21) name: 'Template render error' }
```

for example how do i know in which file this error occured?
